name: fido2_client
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: mojaloop.fido2.fido2_client
        pluginClass: Fido2ClientPlugin
      web:
        pluginClass: Fido2ClientWeb
        fileName: fido2_client_web.dart

  assets:
    - assets/js/fido2_client.js
    # Copied from https://github.com/paroga/cbor-js
    # ideally we would use this dependency properly
    # or even just implement the cbor stuff in dart
    - assets/js/cbor.js
